inherit_gem:
  rubocop-config: default.yml

AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  Exclude:
    - vendor/**/*

Layout/LineLength:
  Exclude:
    - spec/**/*

RSpec/MessageSpies:
  EnforcedStyle: receive
