---
name: test

on:
  - push
  - pull_request

jobs:
  rspec:
    name: "ruby-${{ matrix.ruby }}"
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
        env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - run: bundle exec rspec --color

  rubocop:
    name: rubocop
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
        env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - name: Run rubocop
        run: bundle exec rubocop --parallel --color
