---
name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  rspec:
    name: "ruby-${{ matrix.ruby }}"
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.4"
          - "3.3"
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"

    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_WITHOUT: development

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec --color --format RSpec::Github::Formatter --format documentation
      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  rubocop:
    name: rubocop
    runs-on: ubuntu-24.04

    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_WITHOUT: test

    steps:
      - uses: actions/checkout@master
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - run: bundle exec rubocop --parallel --color
